#! /usr/bin/env python3
# -*- coding:Utf8 -*-

#renvoie le plus grand de trois nombres"

def maximum(a,b,c) :
    if (a > b and a > c) :
        return a
    elif (b > a and b > c) :
        return b
    return c

# test :
print(maximum(4.5, 5.7, 3.9))
print(maximum(8.2, 2.1, 6.7))
print(maximum(1.3, 4.8, 7.6))
